### ISSUE TITLE
Crash with `MCVideoTrack.removeRenderer()`

### ISSUE THREAD

**Issue by DanielKrofchick** [millicast/millicast-sdk-swift-package#1]
We are seeing a repeatable crash in the wild when calling `MCVideoTrack.removeRenderer()`, but so far have been unable to reproduce locally, and it may occur under very specific conditions,

> Fatal Exception: NSGenericException
*** Collection <__NSArrayM: 0x303da0ed0> was mutated while being enumerated.

My guess is there is a codepath in the framework that is not thread safe, and as the crash states, the `MCIosVideoRenderer` is removed immediately on call, while some other enumeration is in flight.

Do you have any insight into this crash, or anything we could be doing on our end to protect against this?

**Comment by djova-dolby** [comment]
https://github.com/millicast/millicast-native-sdk/issues/26
